/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */

plugins {
    java
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

version = "0.0.1"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

javafx {
    version = "17"
    modules = listOf("javafx.base")
}

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDir(listOf("src"))
        }
    }
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.17.0")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.17.0")
    implementation("org.javatuples:javatuples:1.2")
}

tasks.register<JavaExec>("runMain_tcp") {
    group = "application"
    mainClass.set("tcp/Main_TCP")
    classpath = sourceSets.main.get().runtimeClasspath
    standardInput = System.`in`
}

tasks.register<JavaExec>("runMain_udp") {
    group = "application"
    mainClass.set("udp/Main_UDP")
    classpath = sourceSets.main.get().runtimeClasspath
    standardInput = System.`in`
}